import type { Company, Industry, Robot } from '@/lib/types';

export const industries: Industry[] = [
  {
    id: 'commercial-cleaning',
    name: 'Commercial Cleaning Robots',
    shortName: 'Cleaning',
    description: 'Autonomous floor care and facility management systems for enterprise environments.',
    focus: 'Autonomous sanitation, fleet control, and facility uptime.',
  },
  {
    id: 'warehouse-automation',
    name: 'Warehouse Automation Robots',
    shortName: 'Warehouse',
    description: 'Material handling and order fulfillment platforms for complex logistics networks.',
    focus: 'Pick, move, sort, and orchestrate high-throughput operations.',
  },
  {
    id: 'construction',
    name: 'Construction Robotics',
    shortName: 'Construction',
    description: 'Precision robotic systems for jobsite productivity, safety, and quality control.',
    focus: 'Site automation, concrete handling, and inspection workflows.',
  },
  {
    id: 'medical',
    name: 'Medical Robotics',
    shortName: 'Medical',
    description: 'Surgical and clinical robotics designed for regulated care environments.',
    focus: 'Precision intervention, assistive motion, and sterile workflows.',
  },
];

export const companies: Company[] = [
  {
    id: 'aegis-ops',
    name: 'Aegis Operations',
    category: 'commercial-cleaning',
    location: 'Chicago, USA',
    yearFounded: 2014,
    summary: 'Enterprise floor-care robotics for hospitals, airports, and high-traffic retail networks.',
    tags: ['Fleet management', 'Disinfection', 'Facility ops'],
    robots: ['Aegis Sweep X3', 'Aegis SteriCart'],
  },
  {
    id: 'northstar-logix',
    name: 'Northstar Logix',
    category: 'warehouse-automation',
    location: 'Cincinnati, USA',
    yearFounded: 2008,
    summary: 'Autonomous pallet movers and order-fulfillment robotics for distribution centers.',
    tags: ['AMR', 'Sortation', 'Warehouse orchestration'],
    robots: ['Northstar Mover 8', 'Northstar Sorter Pro'],
  },
  {
    id: 'terraform-build',
    name: 'Terraform Build Systems',
    category: 'construction',
    location: 'Austin, USA',
    yearFounded: 2011,
    summary: 'Robotic systems for masonry support, site inspection, and concrete workflow automation.',
    tags: ['Jobsite robotics', 'Inspection', 'Concrete'],
    robots: ['TerraLay 2', 'TerraScan S1'],
  },
  {
    id: 'medivolve',
    name: 'MediVolve Robotics',
    category: 'medical',
    location: 'Boston, USA',
    yearFounded: 2010,
    summary: 'Sterile assistive robotics and surgical platforms for precision care delivery.',
    tags: ['Surgical', 'Assistive', 'Regulated workflow'],
    robots: ['MediArm X', 'MediAssist Lite'],
  },
];

export const robots: Robot[] = [
  {
    id: 'aegis-sweep-x3',
    name: 'Aegis Sweep X3',
    companyId: 'aegis-ops',
    category: 'commercial-cleaning',
    application: 'Large-floor sanitation',
    deployment: 'Hospital campuses',
    payload: '120 kg',
    autonomy: '8 hours',
    description: 'Coordinates multi-zone cleaning routes with mapped obstacle avoidance and service reporting.',
  },
  {
    id: 'aegis-stericart',
    name: 'Aegis SteriCart',
    companyId: 'aegis-ops',
    category: 'commercial-cleaning',
    application: 'Disinfection logistics',
    deployment: 'Airports and transit hubs',
    payload: '180 kg',
    autonomy: '10 hours',
    description: 'Supports high-frequency sanitation workflows with autonomous cart delivery and docking.',
  },
  {
    id: 'northstar-mover-8',
    name: 'Northstar Mover 8',
    companyId: 'northstar-logix',
    category: 'warehouse-automation',
    application: 'Pallet transport',
    deployment: 'Distribution centers',
    payload: '800 kg',
    autonomy: '12 hours',
    description: 'Moves goods between staging zones with real-time fleet coordination and route optimization.',
  },
  {
    id: 'northstar-sorter-pro',
    name: 'Northstar Sorter Pro',
    companyId: 'northstar-logix',
    category: 'warehouse-automation',
    application: 'Order sorting',
    deployment: 'E-commerce fulfillment',
    payload: '300 kg',
    autonomy: '16 hours',
    description: 'Integrates with conveyor and WMS systems for high-throughput parcel sorting.',
  },
  {
    id: 'terra-lay-2',
    name: 'TerraLay 2',
    companyId: 'terraform-build',
    category: 'construction',
    application: 'Material placement',
    deployment: 'Commercial builds',
    payload: '650 kg',
    autonomy: '6 hours',
    description: 'Automates repetitive placement tasks while maintaining tight tolerance and worksite safety.',
  },
  {
    id: 'terra-scan-s1',
    name: 'TerraScan S1',
    companyId: 'terraform-build',
    category: 'construction',
    application: 'Site inspection',
    deployment: 'Vertical construction',
    payload: '90 kg',
    autonomy: '7 hours',
    description: 'Captures scan data for progress verification and dimensional quality checks.',
  },
  {
    id: 'medi-arm-x',
    name: 'MediArm X',
    companyId: 'medivolve',
    category: 'medical',
    application: 'Surgical assist',
    deployment: 'Operating rooms',
    payload: '45 kg',
    autonomy: '4 hours',
    description: 'Supports minimally invasive procedures with stable articulation and repeatable motion control.',
  },
  {
    id: 'medi-assist-lite',
    name: 'MediAssist Lite',
    companyId: 'medivolve',
    category: 'medical',
    application: 'Care support',
    deployment: 'Clinical suites',
    payload: '35 kg',
    autonomy: '8 hours',
    description: 'Assists clinical teams with sterile transport and assistive manipulation in regulated settings.',
  },
];

export const categorySummary = industries.map((industry) => ({
  ...industry,
  companyCount: companies.filter((company) => company.category === industry.id).length,
  robotCount: robots.filter((robot) => robot.category === industry.id).length,
}));
